### ISSUE TITLE
Should fman get a new plugin directory structure?

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#133]
fman currently loads plugins from the `Plugins/` subdirectory of the [data directory](https://fman.io/docs/data-directory). For instance:

 * `{data directory}`
   * `Plugins`
     * `OpeniTerm2`
     * `StatusBarExtended`
     * `...`
     * `User`

The `User` plugin is always loaded last. This lets it overwrite the settings of all other plugins, and thus makes it a good place to put your custom settings.

Up until now, you installed other people's plugins by manually downloading and placing them inside the `Plugins/` directory. I'm currently working on feature #103 to get rid of this manual step and let you install plugins via a command inside fman.

I mention in #103 that downloaded plugins would be placed in `Plugins/` as `.zip` files. It turns out that this is not possible for technical reasons. I have to extract downloaded plugins somewhere.

The question is, where do I put downloaded plugins? I'm wary of just putting them in `Plugins/`, for several reasons:
 * I don't want the user to be tempted to make modifications to downloaded plugins, because these changes will be overwritten when plugins are updated.
 * It makes it difficult to distinguish "your own" plugins from downloaded ones.
 * Say you want to sync "your" plugins to the cloud somehow. If there is a directory that contains your plugins and your plugins only, you can just sync that folder. But if the directory also contains other plugins (which are continually modified by fman), things may become more difficult.

How about the following?

 * `{data directory}`
   * `Plugins`
     * `User`
   * `Plugins (third-party)`
     * `OpeniTerm2`
     * `StatusBarExtended`
     * `...`

Suggestions would be much appreciated.

**Comment by kek91** [comment]
That's a great question. At first I wasn't sure but the more I think about it I think you're right. Having a second directory for "managed" plugins is a clear warning for "do not touch these files" - if you must make changes, make a copy to your "local" plugin directory first.

Also, I'd like fman to ask the user first whether or not to update all plugins with a simple "Update now" or "Later" button. Because I might not want the newest update for several reasons:
- New bug was discovered
- Plugin "change of direction" / bloated features
- Connected to mobile broadband with limited internet data

Some counter-points just for discussions sake:

- Most people would realize the risk when modifying a third-party plugin and will make a copy first. If not, it's the users fault. I say most people because someone will always forget (speaking from experience I learned the hard way when updating a plugin I had done some modifications in for a web CMS - but that was my fault).

- Github downloaded plugins will have `-master` suffix in filename (or whatever else branch the release is tagged on) so it's rather easy to spot local plugins vs those downloaded from Github

- Ok no counter point here, this could be fatal :) I already imagine some ugly sync conflict opportunities here. I currently have fman data directory synced in Dropbox (thanks for symlink tip which worked great btw!) so I'm excited to see how that'll work out :)

Overall I think you're into something and it might be a good idea to split "local" plugins vs "managed"/Github plugins. Interested to hear what other people think as well!

**Comment by macosxguru** [comment]
I like the idea of separating the user plugins from downloaded plugins but I don't like two plugin folders. The basic structure can be the one which is in operation now. 

User plugins get into the User folder. The rest of the downloaded plugins are in the plugins folder. They are separated, why would an user make changes to the downloaded plugins and expect the changes to last over updates?

For backing up, the user would just backup the User folder.

Is there something wrong with this organization schema?

macosxguru

**Comment by mherrmann** [comment]
Thank you both very much for your thoughts.

> I'd like fman to ask the user first whether or not to update all plugins with a simple "Update now" or "Later" button.

I can make plugin updates configurable. But I don't want fman to ever disrupt people in their work flow with "do you want to update?" popups. I feel very strongly about this because I hate such popups with a passion.

> They are separated, why would an user make changes to the downloaded plugins and expect the changes to last over updates?

I believe it's just very tempting to modify plugin files when they're right there. Some people may think:

> I want to change setting ABC of this plugin. Oh look, there is a file `Settings.json` with the value I want to change! I'll just quickly edit this.

For this reason, I don't think I really want to have third-party plugins right next to (say) the User plugin.

> I don't like two plugin folders

How about this?

 * `{data directory}`
   * `Plugins`
     * `User`
       * `Settings`
         * `Core Settings.json`
     * `Third-party`
       * `OpeniTerm2`
       * `StatusBarExtended`
       * `...`

So downloaded plugins would go into `Plugins/Third-party`. Your settings would go into `Plugins/Users/Settings`. And if you want to write a new plugin, you can develop it in `Plugins/User/YourPlugin`.

**Comment by macosxguru** [comment]
I like that much better. All plugins are together. They are separated by source within the plugin folder. Good stuff.

macosxguru

**Comment by mherrmann** [comment]
Do you have an opinion on this @raguay?

**Comment by mherrmann** [comment]
fman 0.3.9 is out with the new plugin directory structure as specified in my previous comment :)
