### ISSUE TITLE
Only visible files are show on windows

### ISSUE THREAD

**Issue by stadub** [fman-community/fman#141]
In the windows explorer is possible to set "show all files" but there no such possibility to make hidden files visible in the fman

**Comment by mherrmann** [comment]
Please try `Ctr+Shift+P` to show the Command Palette and type "hidden". The command "Toggle Hidden Files" should be suggested. Press Enter. fman should now display hidden files as well. You will also be shown the shortcut for this command in the Command Palette: `Ctr + .`

Does this work for you?

**Comment by stadub** [comment]
seems it's better to look through all the abilities before adding the issue:) Thanks a lot)

**Comment by mherrmann** [comment]
:)

**Comment by nhu** [comment]
Can we add this to the documentation? This is a basic feature and should have a higher visibility. Maybe a separate documentation page for the command palette commands with a short description. 
I personally had to search the github issue list unfiltered with the term "hidden" to find this feature.
I also searched for preferences for fman because the command palette feature didn't came to my mind because I am not used to it yet.

Cheers

**Comment by mherrmann** [comment]
Sorry you had a bad experience @nhu. Here's my best idea: When people can't find this feature, they will very likely google for "fman show hidden files". Would you agree? If yes, I could write a blog post that would most likely appear as the first result on Google and explain how it works.

I don't know if you saw but showing hidden files is mentioned at the bottom of the [Shortcuts page](https://fman.io/docs/shortcuts) of fman's documentation.

**Comment by nhu** [comment]
Wow sorry my bad. I actually looked at the shortcuts page but I've overseen it. So it seems to be that everything is fine ;-)

**Comment by mherrmann** [comment]
No problem :-) I wrote the [blog post](https://fman.io/blog/show-hidden-files-in-fman/) I mentioned now, to help others Googling for it in the future.
