### ISSUE TITLE
Ever thought of making it open source?

### ISSUE THREAD

**Issue by csarnataro** [fman-community/fman#148]
I've been using it since just a couple of hours and I kinda have the impression is the file manager I was waiting on Mac (being a paying customer of TotalCommander).

But to be honest, I wouldn't pay 14 € for a software with 147 open issues/bugs, maintained by few developers (possibly only one), with missing features like:
- Multi rename https://github.com/fman-users/fman/issues/60
- Open with https://github.com/fman-users/fman/issues/61
- Resize column dynamically https://github.com/fman-users/fman/issues/72
- Better keyboard interaction https://github.com/fman-users/fman/issues/62
- Treat zip like folders https://github.com/fman-users/fman/issues/37
- FTP/SFTP support https://github.com/fman-users/fman/issues/30 and https://github.com/fman-users/fman/issues/31
- and others.

Also I would like to be able to be able to implement some plugins with a better understanding of the underlying API.
E.g. I installed the QuickLook plugin, it works fine but I cannot "quick look" the next file without closing the Dialog, using only arrow down. How can this be implemented?

In any case thank you for this software, being created for power-users, it would be nice if power-users could contribute to it.

**Comment by csarnataro** [comment]
Closing this issue since I've just read your comment on "open source promise".
I think this comment clarifies your thoughts on it. 
https://fman.io/blog/transparency/#open-source-promise

**Comment by mherrmann** [comment]
Hi Christian,

you already closed the issue but the points you raise are so interesting that I want to reply.

Firstly, thank you for the kind words. I initially started fman because I missed Total Commander when I switched to Mac from Windows. But also TC is showing its age. I'm glad you like fman.

fman's goal is to revolutionise the file manager niche like Sublime Text has revolutionised text editors. This requires years of full-time development effort. I am willing to invest these years. The question is, how to make this possible.

I seriously considered open sourcing fman and wrote an early [blog post](https://fman.io/blog/fmans-business-strategy/) about this. The summary is that if I'm to work on fman full-time, I need an income, and open sourcing would make this difficult if not impossible. If you're interested, please read the blog post. Maybe you have an idea.

If you think 14€ is too much, then please find another file manager. Seriously. There are plenty of options out there. I've invested 1302 hours so far into fman and am currently living off my savings and passive income to be able to work on it. 14€ is ridiculously cheap (also in comparison to other paid alternatives.) So really. If you think it's too much then please go find another file manager and don't come back.

I see you found the [open source promise](https://fman.io/blog/transparency/#open-source-promise). This is insurance for you because, yes, I am the only person working on fman full-time. But plenty of people have contributed their time writing plugins, tutorials, blog posts etc. I am not alone in this.

I understand you'd like to see the code to be able to better understand the API. fman implements most of its functionality using its own API, in a plugin called [Core](https://fman.io/docs/core-plugin). You can find the full source code of this plugin in fman's installation directory. Please see the link I just gave to see the precise location.

Because fman uses its own API to implement most functionality, the API is extremely powerful. In this way, power users can contribute like you asked.

Think about the 14€.

Kind regards,
Michael

**Comment by csarnataro** [comment]
Hi Michael,
thank you very much for your feedback. Just let me clarify my comment about the 14€ for a licence. It's not that I don't want to spend them (years ago when I was a Windows user I spent about 28€ for TotalCommander, and they were probably the best 28€ I ever spent for a software).
I just wanted to say that fman is quite promising but currently it lacks a lot of key features I would like to have, before spending 14€.
On the other hand, I don't have any suggestion on what could be the best business model for fman.
And, of course you have the right to ask money also for the current implementation, but I think that I would stick with the "annoying popup" for a while, because I want to evaluate fman a little bit longer, before buying a licence.

**Comment by mherrmann** [comment]
No problem. Thank you for the clarification. My apologies for the harsh words. It's just gutting when you spend a lot of effort on something and then someone comes and asks "why isn't this open source and btw 14€ [which, by the way, is still ridiculously cheap] is too expensive."

And of course - it's your right to evaluate fman until you've decided whether to buy.

**Comment by mherrmann** [comment]
I further expanded on the reasons why fman isn't open source in a [new blog post](https://fman.io/blog/why-fman-isnt-open-source/).

**Comment by Majora320** [comment]
...why not give the source code to paying customers? Github has private orginizations, which you can have your payment widget auto-invite people to, or you could just provide a tarball of whatever release the user pays for.

**Comment by mherrmann** [comment]
@Majora320 So how would I prevent people from putting the source code online publicly, and using it to break fman's copy protection?

**Comment by Majora320** [comment]
Correct me if I'm wrong (I don't own a copy of fman because I prefer using the terminal as my "file manager" -- [z](https://github.com/rupa/z/) is a command-line version of fman's Ctrl+P), but is there anything stopping people from doing this already with the binary? fman looks at first glance to be available via normal download, and there doesn't seem to be any drm in place. Also, I doubt there would be any motivation to steal & publish a one-man project (which you can *already* evaluate for free, and which provided source code when you buy) it. DMCA takedowns could also work, if you find someone distributing the source.

**Comment by mherrmann** [comment]
How would a DMCA notice prevent someone from sharing the sources via torrent?

**Comment by Majora320** [comment]
It wouldn't.

But you're not addressing my other points. The problem with providing source code would be that you're relying on the honor system, trusting your users not to distribute the source. But if I'm correct, you're *already doing this* by providing direct no drm binary downloads of the program. I highly doubt that you're losing revenue from doing this (if anything, you're losing revenue by providing an unlimited free trial), and the same thing applies to the source. I don't see how the sources being leaked would be worse than the binaries, honestly.

The motivation thing is a legitimate point too. Let's pick, say, Adobe Photoshop as an example of a piece of software that is commonly pirated. Although I've never pirated software myself, I imagine there would be a few reasons for doing so:
1. It's expensive
2. It's ubiquitous ("industry standard")
3. It's produced by a large and somewhat disliked company (+ drm)

None of these really apply to fman (although I personally dislike the idea of a $12 yearly update fee, which is almost the cost of the original program - am I really going to get $12 extra value out of updates every year, considering the original product was $14? I'd probably pick a lower value or zero). There's simply no motivation for someone to distribute the source for a relatively cheap, niche, one-man project. Why would someone *want* to hurt your revenue in this situation?

**Comment by macosxguru** [comment]
Every few months there is someone who asserts, "Why don't you make fman open source?"

The easy answer to this question is, "**fman is commercial software. We have no plans or intentions of making it open source**."

Michael, the developer, invariably doesn't answer the question with my suggested answer, he undertakes a debate. A debate which he is never going to win. There are people in the world who look at "open source" as a religion. You are not going to win a debate with that crowd. Give it up. 

macosxguru

**Comment by Majora320** [comment]
@macosxguru 
Oh, please. I am *not* advocating for fman to become open source, nor am I trying to push a "religion" or the GPL. Your comment is intentionally dismissive and tries to create a straw man of me as a FSF evangelizer, which I am not. 

"Open source", as a concept, implies "open development", "free as in beer", and "freedom to distribute". I am advocating none of these things. I am simply requesting that the source code be made available to people who buy the software, which is entirely different from "open source".

**Comment by Majora320** [comment]
(On a side note, it might be a good idea to reopen this issue while it's sustaining ongoing discussion.)

**Comment by mherrmann** [comment]
Thank you very much for chiming in @macosxguru. You're right in everything you say.

@Majora320 there has been plenty of debate on whether to make fman open source. From fman's beginnings, I've approached the question very openly. But I've never found a solution that would not threaten, or even support fman's mission of creating the most awesome file manager in existence. None of the points you raised present, in my eyes, a viable solution to the problem. As such, I am ending the debate here right now.
