### ISSUE TITLE
Shift+Delete to delete file without moving it to Trash

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#180]
Sometimes it is faster to delete files directly, without moving them to Trash (or Recycle Bin on Windows).

**Comment by macosxguru** [comment]
This scares me. I don't want to accidentally delete something and then not have the ability to change my mind. 

Even if the command is implemented, I would like the option of having no keyboard command set for it. In case the user wants to explicitly enable the keyboard command, they can add it to their keybindings file.

macosxguru

**Comment by mherrmann** [comment]
It's a common feature in (at least) Windows-based file managers. For instance, I believe Total Commander has it. It's useful when you're sure you won't need the files again, because files can be deleted much faster when they're not put in the Trash.

The command would ask you something along the lines of "Are you sure you want to PERMANENTLY delete those files? This action cannot be undone." before proceeding. So I don't think it would be that bad(?) The (imho good) default key binding Shift+Delete is also not "easily" available on Mac (unless you have an external keyboard). So on platforms (Win, Linux) where it's a common feature among file managers, it would be there while on macOS, the user would be unlikely to invoke it by accident. I think that's fair?

**Comment by mherrmann** [comment]
I just implemented this. It will go live with version 0.5.3 - hopefully next week.

**Comment by mherrmann** [comment]
Version 0.5.3 is live - finally :)
