### ISSUE TITLE
fman fails to launch on Ubuntu 17.04

### ISSUE THREAD

**Issue by canadank0** [fman-community/fman#198]
I have problem to run fman on ubuntu 17.04. Im trying to run it on different machines with 17.04 and no luck.

**Comment by mherrmann** [comment]
What do you get as output when you run `/opt/fman/fman` in a terminal?

**Comment by canadank0** [comment]
Traceback (most recent call last):
  File "fman/main.py", line 1, in <module>
  File
"/root/dev/fman/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py",
line 389, in load_module
  File "fman/__init__.py", line 1, in <module>
  File
"/root/dev/fman/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py",
line 389, in load_module
  File "fman/clipboard.py", line 2, in <module>
  File
"/root/dev/fman/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py",
line 389, in load_module
  File "fman/util/qt.py", line 3, in <module>
  File
"/root/dev/fman/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py",
line 573, in load_module
ImportError: libpng12.so.0: cannot open shared object file: No such file or
directory
Failed to execute script main

-Daniel

**Comment by MartyBeGood** [comment]
Ran into the same problem and the solution is less than obvious. Ubuntu 17.04 ships with libpng16 instead of libpng12, so fman does not find that.

You can install the required package from here:
http://cz.archive.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
Source: https://askubuntu.com/questions/915477/install-libpng12-on-17-04

Would be nice to get some sort of lead when launching `fman` or the result of `which fman` in a terminal instead of them just failing silently ;)

**Comment by mherrmann** [comment]
Thank you for sharing the solution @MartyBeGood. I will also fix this so fman is able to start on Ubuntu 17.04 on its own, without manual changes.

**Comment by mherrmann** [comment]
Fixed with fman 0.5.8 ([Changelog](https://fman.io/changelog)) 🎆
