### ISSUE TITLE
fman should use backslashes in paths on Windows

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#212]
Currently on Windows fman returns paths with slashes, e.g. C:/swapfile.sys . All paths on Windows should use backslashes, e.g. C:\swapfile.sys .
I bumped into this issue when working with plugin API DirectoryPaneCommand.pane.get_file_under_cursor() function. I presume, that this might be problem only on some functions, as copy/move dialogs and current path display are using backslashes as folder separators.

**Comment by mherrmann** [comment]
Could you give a specific example where the back slashes present a problem?

**Comment by joshas** [comment]
When working with Windows APIs, e.g. ctypes.windll.shell32.ShellExecuteExW , slashes mostly work, but in some special cases I get errors. Then, if I manually replace slashes with backslashes, API call works.

**Comment by mherrmann** [comment]
I see. I'll have to consider the ramifications for existing plugins. I'll keep it in mind.

**Comment by mherrmann** [comment]
As of version 0.7.0, fman's API functions return URLs instead of paths. Eg. `file://C:/swapfile.sys` instead of  the previous `C:/swapfile.sys`. There is now a new function, `as_human_readable` that lets you obtain the path - with backslashes on Windows - from the URL:

    from fman.url import as_human_readable
    as_human_readable('file://C:/swapfile.sys') # returns C:\swapfile.sys

Note that `as_human_readable` leaves non-`file://` URLs unchanged. Eg. `as_human_readable('zip://foo')` returns `zip://foo`. To handle this, the recommended way is for plugins to use another new function to check if they are dealing with a `file://` URL:

    from fman.url import splitscheme
    url = self.pane.get_file_under_cursor()
    if not url:
        show_alert('No file is selected!')
        return
    scheme, path = splitscheme(url)
    if scheme == 'file://':
        # OK, as_human_readable(...) will return a local file path with backslashes on Windows:
        local_file_path = as_human_readable(url)
        # do something with local_file_path...
    else:
        show_alert('Sorry, only local files are supported for now.')

Because obtaining a path with backslashes on Windows is now possible using the above, I am closing this issue.
