### ISSUE TITLE
Favorites plugin not working on paths that are not under c drive

### ISSUE THREAD

**Issue by CorrectHorseBatteryStapple** [fman-community/fman#225]
Trying to add favorite location in D:\ drive raises exception "Paths don't have the same drive"

![image](https://user-images.githubusercontent.com/17809057/30764337-b394169c-9fea-11e7-9f88-d2e8ada42872.png)

This is very important feature since it allows even faster navigation without thinking about paths.
Thanks.

[Windows 7 x64]

**Comment by mherrmann** [comment]
Sorry for the trouble. This is a bug of the Favorites plugin, not fman. I would ask you to report it on the plugin's issue tracker. In fact, the bug seems to have already been captured there by an [issue](https://github.com/raguay/favorites/issues/2). That would be the right place for discussion of the bug.
