### ISSUE TITLE
macOS .app in fman behaves as directory

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#230]
Pressing enter on .app file (macOS) shows its contents, as it were a directory. There's no way to launch .app from fman. Also, .app file size is not displayed.

**Comment by raguay** [comment]
That is because it is a directory. Press `<cmd>-<enter>` and it will launch it. This behavior is what I like, but it might be counter intuitive to a novice user. Maybe an option to reverse this behavior?

**Comment by joshas** [comment]
Would be nice to have an option to launch .app files from fman directly. Maybe opening .app files could be done with some modifier key or different key combination. Total Commander on Windows has Ctrl+PageDown hotkey to open packed files, even if they are associated with some program.

**Comment by raguay** [comment]
By the way, the `<cmd>+enter` only works if you have the `Mac Open` plugin. Once you add that plugin, simply launch by `<cmd>+enter`.

I just noticed that my last reply isn't showing the key assignments properly.

**Comment by mherrmann** [comment]
Someone already pointed this out once but I can't find an existing issue about it. Maybe it was per email.

What @raguay said is correct. `.app` "files" are in fact directories. I encounter/use this sometimes when developing fman on Mac.

I would rather not change the current behavior. They are directories. It's just that macOS treats them in a special way. But they really are directories.

The workaround as pointed out by @raguay is to use the MacOpen plugin.

I'll close this issue for now as a "wontfix". If many more users are confused by the default behavior, we can revisit it. But I'm quite strongly against the "magic" of treating directories differently just because they have a different extension.

**Comment by joshas** [comment]
Installed MacOpen plugin and it's good enough for me. Would be nice if this functionality was available in fman out of the box.
