### ISSUE TITLE
Rightmost column (Modified) obscured by vertical scroll bar

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#242]
fman 0.7.0 automatically resizes columns as you enter directories or as you resize the window. This does not take into account the vertical scroll bar. If there are only few files and no vertical scrollbar, the column contents are visible. But if there are more files and the vertical scrollbar appears, the end of the Modified column is cut off by the scrollbar.

**Comment by kszcode** [comment]
Thank you, this feature is great!

**Comment by mherrmann** [comment]
@kszcode you mean the feature that automatically resizes columns? Because here we're talking about a bug and I'm confused why you would say a bug is great ;-)

**Comment by kszcode** [comment]
You are right, I'm sorry, I just noticed the feature, which I think it's great.
As far as the bug goes, I don't really see it as a problem, because I would assume that people will usually have enough resolution to display most of the file length.
Also right now when I double click the separator, the file size and date columns get shifted.

**Comment by mherrmann** [comment]
I see. Thanks for clarifying!

**Comment by mherrmann** [comment]
Fixed in version 0.7.3.
