### ISSUE TITLE
Calling fman from spotlight/alfred does not bring it to front

### ISSUE THREAD

**Issue by kszcode** [fman-community/fman#259]
FMAN does not come to the front end when selecting it from spotlight, if fman is already open.

If FMAN is not yet open then it will start on on the foreground.

As far as I can tell this is happening since the version with the zip file 0.7.0.

**Comment by mherrmann** [comment]
You're right! This used to be a bug in old fman versions (#5). I have no idea why it has come back. I will check it out.

**Comment by raguay** [comment]
Not sure if it is related to this or not, but uBar 4 on the Mac is showing two icons for fman since the 0.7.* release: one responsive to clicking and the other is non-responsive. Therefore, there must be two processes running where one isn't suppose to have graphics. But, when you try to bring it forward by that non-responsive process, it doesn't do anything. Using top, there are two fman processes running. That might be the root of the issue here if Alfred/Spotlight are referencing that non-responsive process.

**Comment by mherrmann** [comment]
I think it is related @raguay.

I found and fixed the cause of the problem. Will go live with upcoming release 0.7.5.

**Comment by mherrmann** [comment]
Release 0.7.5 is out and fixes this issue.
