### ISSUE TITLE
Synced Browsing

### ISSUE THREAD

**Issue by yolpsoftware** [fman-community/fman#262]
WinSCP has a very cool feature that I would love to see in fman.

If you enable "synchronized browsing", then any folder navigation you do on the left is repeated on the right, and vice versa. If a folder on the left does not exist on the right, then the user is asked whether they want to create it.

**Comment by mherrmann** [comment]
Good suggestion! It turns out this is very easy to implement via fman's plugin API. So I just implemented it: [SynchronizedBrowsing](https://github.com/mherrmann/SynchronizedBrowsing). Please note that if you get a `FileNotFoundError` when installing the plugin, you have to manually create the `Third-party` directory mentioned in the error message. This is a [bug](https://github.com/fman-users/fman/issues/263) that will be fixed with upcoming release 0.7.6. Sorry for the inconvenience.
