### ISSUE TITLE
Command 'OpenDirectory' raised error.

### ISSUE THREAD

**Issue by wpirtle** [fman-community/fman#296]
I am getting the following error when attempting to open a drive letter.
![image](https://user-images.githubusercontent.com/2790627/35535235-902037ee-0508-11e8-8a97-76f6c6cf6580.png)

**Comment by wpirtle** [comment]
I forgot to tell you, I am running Windows 10 x64 and the latest version of fman v0.8.7.
Wayne

**Comment by raguay** [comment]
You need to remove the plugin and re-install it. That error is due to an older version that has been fixed. The command has been renamed to not conflict with an internal command that doesn't specify the url parameter. If you re-assigned the command to a different hotkey, you will need to change the command name.

**Comment by mherrmann** [comment]
Yes, thank you @raguay. If the problem persists after removing your plugins, try manually deleting the `Plugins` directory in your [data directory](https://fman.io/docs/data-directory) @wpirtle. If you want to keep your settings (such as key bindings), back up the `Plugins/User/Settings` folder first.
