### ISSUE TITLE
API: get_application_commands returns a small subset of all available commands

### ISSUE THREAD

**Issue by ababak** [fman-community/fman#305]
I expect to be able to get all the currently available commands. 
`get_application_command_aliases('Open terminal')` also does not return an alias for the requested command.

**Comment by mherrmann** [comment]
I'm pretty certain this is because [get_application_commands(...)](https://fman.io/docs/api#get_application_commands) only returns [ApplicationCommands](https://fman.io/docs/api#ApplicationCommand). But `Open terminal` for example is a [DirectoryPaneCommand](https://fman.io/docs/api#DirectoryPaneCommand). You will likely want to use [DirectoryPane.get_commands(...)](https://fman.io/docs/api#DirectoryPane.get_commands) as well.

Does this let you fix the problem you described? If yes, I'll update the API documentation to make this clearer.

**Comment by ababak** [comment]
Yes, you are right, sorry for the confusion.

**Comment by mherrmann** [comment]
Okay, thanks! I'll update the docs.

**Comment by mherrmann** [comment]
[Docs](https://fman.io/docs/api#get_application_commands) updated.

**Comment by ababak** [comment]
Perfect, thanks!

**Comment by ababak** [comment]
Already updated my plugin.
