### ISSUE TITLE
Make alternative keywords for some commands to appear in the Command Palette results

### ISSUE THREAD

**Issue by ababak** [fman-community/fman#314]
I thought that creating zip archives is not supported yet. I tried "zip" and "archive" keywords. What about adding keywords to some commands so that they can be more easily found in the Command Palette?

I mean the command stays "Pack" but will come up when I type "zip". Maybe these keywords could appear aside the "Pack" word dimmed to show the reason why this command has appeared in the results list.

**Comment by ababak** [comment]
I've made a simple mockup to illustrate the idea
![tags_mockup](https://user-images.githubusercontent.com/11334363/36061882-f7482c8c-0e69-11e8-8922-516cfbdd95b0.png)

**Comment by mherrmann** [comment]
That's a great idea. Also, thank you for the mockup. What do you think of displaying the `Pack` command as `Pack to archive (.zip, .7z, .tar)`? Then it would appear under any of the keywords "zip", "archive" and "pack":

![image](https://user-images.githubusercontent.com/1076393/36092811-f416011c-0fe8-11e8-9eb9-54f45b5b5d1f.png)

![image](https://user-images.githubusercontent.com/1076393/36092824-05933ed2-0fe9-11e8-9675-237dbad5dd5b.png)

However, we can also add other aliases for the command (fman makes this possible). In this case, the command would appear Command Palette under multiple names, depending on what the user entered. If you think the single alias `Pack to archive (.zip, .7z, .tar)` is not enough (or not a good name), just let me know.

Thanks!
M

**Comment by ababak** [comment]
Well, modifying the command itself is a good workaround. But I thought that adding alternative names could be a good addition for finding different commands.

**Comment by mherrmann** [comment]
Do you have particular alternative names in mind?

**Comment by ababak** [comment]
Go up = Parent
Quit = Exit (currently, you have two different commands for this, right?)
Terminal = Shell
Delete = Erase
Pack = Zip, Archive, Tar, 7z
Trash = Recycle bin
...to name a few)

**Comment by mherrmann** [comment]
Thank you.

* `GoUp` is already available as `Go to parent directory`. This shows up when the user searches for "parent", so should be okay I think.
* `Exit` and `Quit` are both defined and aliases for the same command. 
* The built-in command `Terminal` has the aliases `Shell`, `Open terminal` and `Open shell`. Should be okay too I think.
* I've never heard of _erasing_ a file. Is that really a term people use?
* Yes, following your suggestion, the `Pack` command now appears for all the keywords you mentioned.
* The command `MoveToTrash` also has alias `Move to recycle bin`. That shows up when the user searches for "recycle bin" so should be fine too I hope.

If you (or other people reading this) can think of other aliases that should be added, just let me know! Otherwise I'll just release the above alias for `Pack` with 0.9.0.

**Comment by mherrmann** [comment]
Implemented the alias for the `Pack` command in 0.9.0.
