### ISSUE TITLE
Shortcut list (F1) extends offscreen on high-res displays.

### ISSUE THREAD

**Issue by nozzlegear** [fman-community/fman#344]
(I'm using Fman on Windows.)

When I press the F1 key to bring up the shortcut list on my Surface Book (3000x2000 resolution), the list extends all the way off the screen and it's difficult to see the few shortcuts near the bottom. The formatting is also messed up and difficult to read.

Sorry for the big image:

![image](https://user-images.githubusercontent.com/2417276/37735637-aaff4082-2d1c-11e8-8bbd-b77c4458ba67.png)

It'd be great if we could resize this little window and scroll through it.

**Comment by kek91** [comment]
Hi, sorry about this. Looks like you're using my [ShowKeyBindings](https://github.com/kek91/ShowKeyBindings) plugin and unfortunately I'm lagging behind on updating the plugins.

I don't think the `show_alert` frame supports a scroll bar, and I can't see any new methods in the [fman api](https://fman.io/docs/api) to open a new window/frame widget, so I suppose the easiest workaround here is to split the output (keybindings) to several columns. Feel free to create an issue at the plugin repository [issue list](https://github.com/kek91/ShowKeyBindings/issues).

Anyway, while the issue was posted here I might as well ask you Michael: do you plan on implementing custom windows in fman api? Sorry if this has already been answered elsewhere

**Comment by nozzlegear** [comment]
Oh shoot, I'm sorry! I thought this was part of fman itself, forgot I installed your plugin. I'll create an issue there in a sec.

**Comment by mherrmann** [comment]
> Anyway, while the issue was posted here I might as well ask you Michael: do you plan on implementing custom windows in fman api? 

Not at the moment, I'm afraid. You can currently do it. But it's not officially supported.

Regarding the present issue, there really should be scroll bars in the alert. This is #97.

**Comment by kek91** [comment]
Yeah, I'm trying to avoid importing Qt and stay with fman api :)
I got an idea to prettify the output (workaround for height and avoid those silly misaligned tabs with `\t`) in the alert box so will do that first, no worries.

**Comment by mherrmann** [comment]
Sounds good :)
