### ISSUE TITLE
Compare directories and/or select files that are not present in the other pane

### ISSUE THREAD

**Issue by gingerbeardman** [fman-community/fman#454]
I often need to compare directories, either to simply spot differences (new/missing file) or to sync them by subsequently copying the extra files to another location. An app can help me by selecting files in one/both panes based on a comparison.

> Looking at the fman way of doing things, there could be a bunch of items (see XYplorer below) in the Command Palette to so the user can easily choose the comparison that suits. It would be super cool if the selection changed as you changed the command in the palette so you could get a preview of how things will turn out? It could be as easy as parsing the output of `diff pane1 pane2`?

Other dual pane apps that do it in a variety of ways...

- [XYplorer](https://www.xyplorer.com/) (Windows) does it using operators on the select function:
![xy1](https://user-images.githubusercontent.com/49612/43214906-a1a015e2-9032-11e8-8830-80c40b7aa2a1.png)
![xy2](https://user-images.githubusercontent.com/49612/43214907-a1b61d56-9032-11e8-9175-2a3d13280ad7.png)

- [Nomad.NET](http://www.nomad-net.info) (Windows) does it in a similar way, but with a more complicated dialog:
![nomad1](https://user-images.githubusercontent.com/49612/43214910-a3fbdde4-9032-11e8-9c77-61bde71eae7c.png)
![nomad2](https://user-images.githubusercontent.com/49612/43214911-a4180884-9032-11e8-9546-c0a9bbfb9d93.png)

- [ForkLift](https://binarynights.com) (Mac) has a sync mode that will show you the files, but you can't select them
![screen shot 2018-07-25 at 19 54 44](https://user-images.githubusercontent.com/49612/43222468-1b3bb806-9048-11e8-9497-67f42d3e4216.png)

- [Double Commander](https://doublecmd.sourceforge.io) (All) is the same: sync mode will show you the files, but you can't select them
![screen shot 2018-07-25 at 21 13 52](https://user-images.githubusercontent.com/49612/43225137-53d35a36-9050-11e8-8b69-81916e057055.png)

- [NimbleCommander](http://magnumbytes.com) (Mac) doesn't have it, but describes it as "must have": https://github.com/mikekazakov/nimble-commander/issues/17

**Comment by mherrmann** [comment]
Interesting. Thank you very much for the detailed analysis and the screenshots.

It would be interesting to know exactly what the use cases for the various options are. For example: If you want to sync the two directories - that is, you want them to have the same contents - there could be a special command that does just that, without fiddling with selections etc. On the other hand, if you merely want to see the differences, there could be another command / way of presenting this information etc.

**Comment by gingerbeardman** [comment]
In this instance it was simply to see the differences.

Sometimes I need to go the extra step and sync/make sure they have the same contents.

**Comment by mherrmann** [comment]
Implemented in [fman 1.4.4](https://fman.io/blog/compare-directories-in-fman/).

**Comment by gingerbeardman** [comment]
Great news! 

Thanks for adding.

**Comment by mherrmann** [comment]
My pleasure :-)

**Comment by kek91** [comment]
Hi @mherrmann :) Quick question. After I run `Compare directories`, all files are still selected so I have to CTRL+D two times to deselect files on both panes. Is this a bug or intended behavior?
So far I've only tested on Ubuntu 18.04 though running xfce desktop environment.

**Comment by mherrmann** [comment]
It's intended :-) I think it makes sense for <kbd>Ctrl+D</kbd> to only affect the current directory. Because surely there will be situations where you only want to deselect the current pane, not both of them.

**Comment by kek91** [comment]
> I think it makes sense for Ctrl+D to only affect the current directory. 

Yes I agree, that's not the issue, you can disregard my "... on both panes" which just added confusion :)

I simply meant that the `Compare directories` function doesn't automatically deselect all files again after selecting them, an unexpected side effect

**Comment by mherrmann** [comment]
I don't understand sorry. Why should it deselect the files after selecting them? If you mean that it should deselect _before_ selecting them, that is what it (should) be doing. If not, that's a bug.

**Comment by kek91** [comment]
I guess the question really is, why does it select files at all? I want to compare two directories, that's it. If I want to select all the files I will press CTRL+A or "Select all".

The function `Compare directories` also does `Select all`, but why? (I get that fman must select all files in order to do the compare operation, but why does they stay selected when the user hasn't explicitly asked to *select* files).

**Comment by mherrmann** [comment]
It doesn't do select all. Only those that are missing (?)

**Comment by kek91** [comment]
Alright, doesn't matter how it does it, but the point is that the files stay selected after closing the `compare directories` dialog.

For instance. Let's say I want to compare these two directories:

![image](https://user-images.githubusercontent.com/1431734/48611829-6807d280-e987-11e8-86e5-f62e01082c65.png)


When I run `Compare directories` it looks like this:

![image](https://user-images.githubusercontent.com/1431734/48611731-25de9100-e987-11e8-8362-e6b34b95911c.png)

All files are selected, and that's ok. But when I press OK to close the dialog, I expect it to deselect all files again (because I didn't have any files selected prior to running the compare operation).

Instead, they stay selected, forcing me to manually deselect all files by pressing CTRL+D (or do something else to trigger deselect)

![image](https://user-images.githubusercontent.com/1431734/48611781-3e4eab80-e987-11e8-85d3-a7d044703578.png)

All in all, its no big issue, just a minor nuisance :)

**Comment by gingerbeardman** [comment]
@kek91 as the person who requested this feature, the way I use this feature is described in the first sentence of the OP. As bullets I've reproduced it here as follows:

1. compare directories
2. keep selection
3. work with selection, eg. copying files present in one dir to the other where they are missing)

That said, maybe you want to back out of the comparison another way? Maybe you just change your mind, or have no use for the selection going forward (this sounds like you)?

So, maybe a second button could be added, then the two buttons would be:
- Keep (selection) [default]
- Cancel (selection)

PS: I'm not a fan of using <kbd>OK</kbd> and <kbd>Cancel</kbd> as button labels, at least the default should be more descriptive especially when the loss of information/state will occur. [See the macOS Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/alerts/)

**Comment by mherrmann** [comment]
Yes, the use case described by @gingerbeardman is the intention behind the current implementation of the feature: They files that differ stay selected because you usually want to do something with them. You might copy them to the other pane, for example.

To be honest (and do point out if I'm wrong), I think it's pretty reasonable for the files to stay selected. It enables a lot of use cases and <kbd>Ctrl+D</kbd> is really not that difficult, even if you have to do it twice. We could change the dialog to end with _"Do you want to keep the selection? Yes/No"_ This would enable a quick binary "I just want to know if the directories are the same".  Not sure if it is that common though?

**Comment by kek91** [comment]
Aha I see, I understand your points, thanks for the clarification. That's absolutely a valid reason. 

I really like this function as I have several copies of same projects scattered through computers and network storage locations, but I use other tools for the synchronization part so I just like to do the comparison.

Great suggestion, but there's no need for modifications yet, let it stay as it is. If you do receive any other complaints then perhaps we can create a new issue to slightly change the dialog to have two buttons to keep or discard selection (and as @gingerbeardman mentions, keep "keep"/"OK" as default so it doesn't break workflow of current users :))

**Comment by mherrmann** [comment]
:+1:
