### ISSUE TITLE
Dropbox Filesystem no longer recognized

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#483]
The Dropbox file system no longer is recognized. The plugin is in the plugin lists, but I can no longer go to the file system. Fman says it's not a recognized filesystem. What changed?

**Comment by mherrmann** [comment]
I'm not sure why that is. (I presume not for you would have mentioned it otherwise.) Do you see anything when you start fman via the Terminal: `/Applications/fman.app/Contents/MacOS/fman` ?

**Comment by raguay** [comment]
Nope. Nothing shows in the terminal. Just this error message:

Command 'GoToDropboxFileSystem' raised error.


Traceback (most recent call last):

File "fman/impl/plugins/command_registry.py", line 106, in _execute_command

File "/Users/raguay/Library/Application
Support/fman/Plugins/Third-party/DropboxConnect/dropboxconnect/__init__.py",
line 440, in __call__

self.pane.set_path('dropbox://')

File "fman/__init__.py", line 130, in set_path

File "fman/impl/widgets.py", line 109, in set_location

File "fman/impl/model/__init__.py", line 43, in set_location

File "fman/impl/model/__init__.py", line 51, in _set_location

File "fman/impl/plugins/mother_fs.py", line 120, in resolve

File "fman/fs.py", line 102, in resolve

FileNotFoundError: dropbox://


Which looks like the file system isn't registered, but I haven't changed
the code at all and it should be the same.

**Comment by mherrmann** [comment]
I think I know why: fman calls `DropBoxFileSystem#resolve('')`, which (as of fman 1.1.6) calls `#exists('')`. The reason for this is that per the API docs `resolve(...)` is supposed to raise `FileNotFoundError` if the given path does not exist. Before fman 1.1.6, the default implementation (which `DropBoxFileSystem` inherits) did not do this. Now it does.

The fix for this is probably to change `DropBoxFileSystem#exists(...)` so it returns `True` for an empty path `''`.

Sorry for the confusion. The API docs were correct, but fman's default implementation did not follow them well enough. That's why it was changed.

**Comment by raguay** [comment]
Okay, that does work. I guess the cache doesn't ever get '' stored. I query
the cache each time for that function. I just changed it to always give
true for '' as well.

**Comment by mherrmann** [comment]
Yes, that solution makes sense. Sorry again for the inconvenience. I'm closing this issue. (Feel free to reopen.)
