### ISSUE TITLE
Open packages on Mac

### ISSUE THREAD

**Issue by matangover** [fman-community/fman#493]
On Mac, if I go to the /Applications folder, I didn't find a way to launch an app. Clicking enter, or using the Open command, simply open package contents. In Finder double clicking an App launches it, which is the expected behavior.

**Comment by raguay** [comment]
Install the plugin "MacOpen". I believe the default for it is <cmd>-Enter.
It will then use the open command to open the program. Works great for me.

**Comment by matangover** [comment]
Thanks for tip @raguay. I like this plugin. I believe it should be part of the default fman install. I think Mac users would expect to have a way to launch apps. At least I did :)

**Comment by mherrmann** [comment]
Okay :-) Because this keeps confusing users, I now changed it so the first time you press <kbd>Enter</kbd> on a `.app` in macOS, you get a dialog that tells you about the (new) standard shortcut <kbd>Cmd</kbd>+<kbd>Enter</kbd>:

![mac-app-open-hint](https://user-images.githubusercontent.com/1076393/45079361-a749b580-b0f2-11e8-9a76-b3e958091f3f.png)

This dialog is only shown once.

**Comment by mherrmann** [comment]
Implemented in [fman 1.2.9](https://fman.io/changelog#v1.2.9).

**Comment by matangover** [comment]
Awesome. Thank you Michael for the amazing support. I just bought a license.

**Comment by mherrmann** [comment]
Awesome. Thanks!
