### ISSUE TITLE
Adding a custom context menu item does not work

### ISSUE THREAD

**Issue by IgorKrupenja** [fman-community/fman#504]
Basically, I have been following your guide here https://fman.io/docs/context-menu

1. Create the `$HOME/.config/fman/Plugins/User/Settings/​File Context Menu.json` file.
2. Add the following to the file:

```
[
	{ "caption": "-", "id": "clipboard" },
	{ "command": "about" }
]
```

3. Reload plugins in fman.

No new entry in the menu. This is on an up-to-date Manjaro Linux.
The following did not work either:

```
[
    { "caption": "-", "id": "clipboard" },
    { "caption": "About", "command": "about" }
]
```

**Comment by mherrmann** [comment]
Strange. I just did what you described (with the first snippet). And am getting the context menu entry:

![image](https://user-images.githubusercontent.com/1076393/45094377-6914bc00-b11b-11e8-9d58-564df609822a.png)

Could it be that you right-clicked not on a file, but inside a folder? Because for that, you'd have to define `Folder Context Menu.json`.

**Comment by IgorKrupenja** [comment]
Weird, can no longer reproduce this with 1.3.2. Closing.
