### ISSUE TITLE
Search doesn't prioritize closest match

### ISSUE THREAD

**Issue by CoenraadS** [fman-community/fman#539]
![image](https://user-images.githubusercontent.com/5593825/46569469-f2572280-c955-11e8-8135-8160f6c90e5e.png)

![image](https://user-images.githubusercontent.com/5593825/46569519-ac4e8e80-c956-11e8-823f-726af2164749.png)

I am typing 'proje' to get into my projects folder, which I would expect to be closest match

**Comment by IgorKrupenja** [comment]
This is due to matching being set to `*str*` instead of `str*` starting from 1.3.2. I think the best option solution would be to allow users to configure the desired behaviour in the settings file. @mherrmann, for some more ideas with usage examples, please also see my comment at https://github.com/fman-users/fman/issues/512#issuecomment-425900532.

**Comment by mherrmann** [comment]
That's exactly the case I was worried about when implementing #512. If `str*` is the default, then you can always type in the leading `*` for a substring (rather than a prefix) match. But not the other way around.

I'm somewhat weary of configuration options, because most users will never realize they're there. The default behavior needs to be "good enough". 

@krupenja can't you fix your "dropbox" example by not displaying hidden files? This should get rid of the `.dropbox...` folders, shouldn't it?

I'll think about this a little.

**Comment by rmgk** [comment]
In case you did not consider this: it seems possible to do both for this use case, filter by sub string, but move the cursor to the first prefix match.
At least for my use cases, it seems that prefix match is only preferable for element selection, not filtering.

**Comment by mherrmann** [comment]
That's a very good idea @rmgk. I implemented it this way now. Will go live with fman 1.3.7.

**Comment by mherrmann** [comment]
Implemented in [fman 1.3.7](https://fman.io/changelog#v1.3.7).
