### ISSUE TITLE
payment via PayPal fails

### ISSUE THREAD

**Issue by jrappen** [fman-community/fman#549]
Receiving a:

```text
PayPal could not process your payment. Please try again.
If the problem persists, please pay by card.
```

error. I assume your website has a config issue as using PayPal with other websites works.

**Comment by mherrmann** [comment]
Sorry for the trouble Johannes. The reason is likely similar to [this one](https://support.liveedu.tv/hc/en-us/articles/225999367-I-am-from-Germany-why-does-Paypal-reject-my-subscription-purchase-): PayPal only supports recurring payments if you have a credit card associated with your PayPal account. It's not that fman's website immediately tries to charge you for updates. But the way PayPal's API works, fman's web site has to set up the recurring payment immediately, even if it will only be charged in a year's time (unless you cancel before then).

So, the solution should be to either use a card to pay on fman's web site, or to add a credit card to your PayPal account. Or - to choose not to include updates when purchasing fman :(

**Comment by jrappen** [comment]
@mherrmann Same issue, yes.

Maybe you could add that info for German and Chinese potential buyers.

**Comment by mherrmann** [comment]
You're right, good point. I updated the error message to now say 

> PayPal could not process your payment. If you are based in Germany or China, this can happen when your PayPal account is not linked to a credit card. In that case, please pay for fman by card or de-select automatic updates. Otherwise, you may simply want to try again.
