### ISSUE TITLE
Inverse selection

### ISSUE THREAD

**Issue by kapooostin** [fman-community/fman#577]
I can't find a command to inverse selection. Does `fman` have it?

**Comment by raguay** [comment]
If you look for my plugin "DeSelect", it uses the fman command to toggle_selection. You can bind that to a hotkey to use as a inverse selection type of command.

**Comment by kapooostin** [comment]
Sorry, but how should it help? It just deselects all files, not inverses it. Internal command `toggle selection` toggles selection for, well, selected file not all files in a pane.

**Comment by raguay** [comment]
I just added the command `invert all` to the DeSelect plugin. It will
invert all the selections in the current pane. You will have to remove the
plugin and re-install it to get the change. Let me know if you have any
questions or if it doesn't do what you want.

Richard

**Comment by kapooostin** [comment]
Yeah, thank you! It works perfectly. Maybe the name for the command isn't very obvious. Usually is is called `Invert selection`.

Sidenote: I guess it is the implementation detail, but it is very unusual to see how files are selected, deselected, deleted one by one.

**Comment by raguay** [comment]
It's an artifact of being interpreted commands and the GUI updating on each
iteration. If you could inhibit the GUI update until all done, it would
most likely be faster and less obvious how it works. But, that isn't
currently in the implementation of fman.

**Comment by raguay** [comment]
Actually, the way fman is implemented has the user see results the fastest, but not necessarily performs the fastest. There are tradeoffs both ways and everyone hits the best fit for their programs.

**Comment by mherrmann** [comment]
Thank you Richard!

**Comment by kapooostin** [comment]
I understand the issue with rendering each change. But `fman` selects files with `Select all` in one go, but deselects them one by one. At least it looks like it. Both commands are available in a bare installation of `fman` without any plugins, so it looks inconsistent.

I'm not trying to say that is is bad. But unusual.

**Comment by mherrmann** [comment]
You have a valid point @kapooostin. I agree that it's strange when files are (de-)selected one by one. This also happens with the `Compare Directories` command.

To fix this, I have now added new API functions `.select(files)` and `.deselect(files)` that let plugins (de-)select many files at once. I have also implemented an `Invert selection` command in fman that uses them. I understand that renders the implementation you provided @raguay obsolete. But I believe it is the better solution for fman to have a command for inverting the selection built-in.

The above changes will go live with fman 1.4.6. Thank you both for the feedback and you Richard for helping out.

**Comment by kapooostin** [comment]
Well, the first thing I did this morning was to buy a license for `fman`. Thank you, guys!

**Comment by mherrmann** [comment]
Thank you!!

**Comment by raguay** [comment]
The DeSelect plugin was already obsolete. It got revived for a little while and is again that way. It just shows that plugins that are good enough will lead to features added to the main program. 

On another note while on this subject: I would like an API addition to get a list of files shown in the pane. Querying the file system gives you hidden files as well that you have to sort out. That is why the loop has the try/except statement. Throwing and catching exceptions are fairly expensive in execution time in Python and would not be needed if an API function would just give a list of files currently seen in the pane.

**Comment by mherrmann** [comment]
:+1: 

> I would like an API addition to get a list of files shown in the pane. [...] Throwing and catching exceptions are fairly expensive in execution time in Python and would not be needed if an API function would just give a list of files currently seen in the pane.

I believe that you need the try ... except even when you have such an API function. Consider:

    files = self.pane.get_visible_files() # This would be the new API function
    for f in files:
        self.pane.toggle_selection(f)

It can and will happen that a file disappears after the first line in this snippet. Eg. when the file is deleted by another application. So you'd still need the `try ... except`. But please read on.

The API functions I added, and which will go live with fman 1.4.6, let you perform batch (de-)selections and ignore errors by default. So the above snippet can be written as:

    files = self.pane.get_visible_files()
    self.pane.select(files) # This ignores errors

This is much faster, not because of `try ... except` though, but because it doesn't re-render after every selection.

Finally, out of curiosity I tested how expensive `try ... except` are. And you're right: It's quite considerable.

`perftest1.py`: 

    def f():
        for _ in range(10000):
            pass

`perftest2.py`:

    def f():
        for _ in range(10000):
            try:
                pass
            except ValueError:
                pass

This gives:

    michael:~$ python3 -m timeit 'from perftest1 import f ; f()'
    10000 loops, best of 3: 159 usec per loop
    michael:~$ python3 -m timeit 'from perftest2 import f ; f()'
    1000 loops, best of 3: 212 usec per loop

**Comment by raguay** [comment]
That will be great addition to the API. Yes, I did not take into account
the case where outside program would remove a file. But, looping through
the exception test and being triggered on one or two every now and then is
much faster.

Your test didn't account for an exception happening. That will double the
time again since it creates an exception, passes it on, and destroys the
exception. You see similar slowdowns in other interpreted languages. Not
sure if you can do it or not, but if you can disable garbage collection
until after the loop, that will speed up the loop some as well. Garbage
collection is the largest slowdown in all interpreters!

**Comment by mherrmann** [comment]
Very interesting! :+1:

**Comment by mherrmann** [comment]
The `Invert selection` command and the [select(...)](https://fman.io/docs/api#DirectoryPane.select) and [deselect(...)](https://fman.io/docs/api#DirectoryPane.deselect) API functions are now in fman.
