### ISSUE TITLE
exFAT support?

### ISSUE THREAD

**Issue by AllanLRH** [fman-community/fman#604]
Hi, I am getting the following error in a popup-box when I try to browse an external hard-drive using the exFAT file system (it should have been called _FAT 64_).
I tried to browse it by doing <kbd>Ctrl</kbd>+<kbd>g</kbd>, and entering `G:\` as the path.

```
Command 'OpenDirectory' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 128, in _execute_command
TypeError: __call__() got an unexpected keyword argument 'url'
```

I am running windows 10 Pro. `winver`-info: `Version 1803, (OS Build 12134.471)`.

I downloaded the newest version of fman before submitting this report.

**Comment by mherrmann** [comment]
Unless I am completely confused, <kbd>Ctrl</kbd>+<kbd>g</kbd> is a non-standard shortcut which (I presume) you defined yourself. I further suspect you have something like this in your `Key Bindings.json`:

    {"keys": ["Ctrl+g"], "command": "open_directory"}

If that's the case, then the reason you are getting the error message is not to do with exFAT, but because `open_directory` is not meant to be invoked this way. If at all, it should be just `open`. But that only opens the file under the cursor. What I believe you want is the same behavior as <kbd>Ctrl</kbd>+<kbd>P</kbd>, which you can get via:

    {"keys": ["Ctrl+P"], "command": "go_to"}

**Comment by AllanLRH** [comment]
I reinstalled Windows yesterday, and Fman along with it. Seems to work now.

**Comment by mherrmann** [comment]
Happy to hear it works now :-)
