### ISSUE TITLE
unable to install on Ubuntu 18.10 x64

### ISSUE THREAD

**Issue by ranobrega** [fman-community/fman#651]
Hello
I am unable to install on Ubuntu 18.10 (x64).

The process published on fman's website on https://fman.io/download/thank-you?os=Linux&distribution=Ubuntu, does not work; apt-key returns a timeout.

Additionally, using Ubuntu's Software application, installs a snap that does not work. No files. 

Thanks in advance!

**Comment by mherrmann** [comment]
Hi,

I just tested this in a Ubuntu 18.10 VM (x64). It worked without any problems. I think this is a problem with your local machine, not with fman. The snap is not by me (yet).

I'll close this issue for now. Feel free to re-open or comment if you have evidence that the problem lies with fman (or its server / installation instructions), and not with your specific setup.

Cheers,
Michael

**Comment by ranobrega** [comment]
Ok. I will try with a different setup. Will keep you posted if needed.
Thanks for the support.

**Comment by mherrmann** [comment]
Okay :-) Please do yes, if you find out more.
