### ISSUE TITLE
An idea to loading folder content much faster.

### ISSUE THREAD

**Issue by MohammadGhasemi** [fman-community/fman#659]
It would be great if the content of folders could load faster. I have an idea for that. The software can create an index of all files in the background. So instead of retrieving file information just-in-time, it can use the index. Of course the index would not be always up to date and some users may not like that. So the user should be able to choose which system he wants to use. So I think this can be added as an option to the Ctrl+Shift+p list or as a plug-in.
That you!

**Comment by mherrmann** [comment]
Thank you for the suggestion. fman already does have some such caching mechanism. But it tries to be more up-to-date. Your approach (as you point out) consciously chooses to sometimes show out-of-date information.

In general, I think fman can still improve a lot more in terms of speed using techniques that do not forsake accuracy.

Either way; you mention a plugin. You can already write this yourself. For an introduction, see [this post](https://fman.io/blog/fmans-new-file-system-api/).

I'll close this issue, because I feel the missing accuracy does not belong in "core" fman. But thank you!

**Comment by MohammadGhasemi** [comment]
Thank you for your response
