### ISSUE TITLE
fbs freeze/installer does not run module

### ISSUE THREAD

**Issue by kkagill** [fman-community/fman#689]
Hello, 

Thanks for this great library.
I was trying to connect to `Slack` chatroom via websocket using their library and I found out it was working in  `fbs run`  mode but not in `fbs freeze` and `fbs installer` mode. 

Since I could not find ways to debug in freeze or installer mode in windows 10, I ended up putting this up in a thread. Could you help me to nail down why it's having a bit of problem please?

I created a very simple example.
https://github.com/kkagill/fbs_slack_rtm/blob/master/main.py

pip install fbs PyQt5==5.9.2
pip install slackclient==1.2.1

**Comment by mherrmann** [comment]
Hi,

First, this is fman's issue tracker, not that of [fbs](https://GitHub.com/mherrmann/fbs).

Second, your message "it's working with `fbs run` but not with `fbs freeze`" gives me almost no information. If you had given at least an error message, or some other output you're seeing, I could have tried to give you a hint without having to run your code.

I do appreciate that you created a minimal example. But. I have a lot of projects and don't have time to help people with their scripts. I often get people "Michael, my program isn't working, can you help". But as I said, I have neither the time nor to be honest the inclination to be a free-for-all "just come to me with your problems".

So, I'm closing this issue. If you think what you are experiencing is a bug in fbs, please do open an issue on fbs's issue tracker. Otherwise, I recommend you ask for help on stackoverflow.

Cheers
M
