### ISSUE TITLE
fman reported as malware

### ISSUE THREAD

**Issue by josefblaha** [fman-community/fman#696]
fman's main executable v1.6.6.0 was reported as Win32/Uwamson.A!ml malware by Windows Defender on my computer today. I submitted it as a false positive to MS.

I see that fman has a history of being marked as a false positive by several antiviruses. I would understand that a single antivirus can report a false positive, but looking at the VirusTotal report of my fman.exe, there are many of them:
![image](https://user-images.githubusercontent.com/13222165/67704342-33810100-f9b5-11e9-8027-278a54125956.png)

How is that possible? I doubt that all of them share a same engine, making the same mistake.

Can fman's digital reputation be improved? E.g. by adding a digital signature?

**Comment by mherrmann** [comment]
Thank you for reporting it as a false positive to MS. I'm surprised Windows Defender marks fman as malware now; I haven't released a new version since last month, and haven't gotten any other complaints.

You're right that fman, as somewhat of a niche product, has a [history](https://fman.io/blog/fman-and-antivirus/) of being marked as a false positive. The only solutions to this I can think of would be for me to get an Extended Validation code signing certificate (instead of the normal one I currently have). And to have users like you download fman and report it as safe. I'm not even sure whether I would be eligible for an EV certificate, and either way it would be too expensive and time consuming compared to how much money fman makes. So I think we're stuck with nice users like you telling the various vendors that fman is fine. (For instance, the last time I did this for Windows Defender, MS did quite quickly release an update that marked fman as safe.)

Thanks!
