### ISSUE TITLE
Configure open to use vim

### ISSUE THREAD

**Issue by pburns001** [fman-community/fman#722]
Hi, I'm trying to add an open with Vim command/shortcut for fman on Ubuntu Linux.  I've reviewed the documentation but don't see how to do it.  For example there is no key bindings json file in the config directories.

**Comment by raguay** [comment]
Hi, run the `open with…` command in the command pallet. Then scroll down until you see `Configure`, then click `Add an App`, and then select the application in the finder dialog. Since this command uses the `open` command, it needs to be MacVim or other graphical vim.  If you want to use a terminal vim, you will have to use something like my plugin [OpenWithEditor](https://github.com/raguay/OpenWithEditor). You will have to setup the editor according to the instructions on that page.

**Comment by mherrmann** [comment]
Thank you @raguay!

**Comment by pburns001** [comment]
Thanks, I was able to configure openWith as you instructed, however, I want
to know if it's possible to set default apps for different file types.  For
example, for text files on Ubuntu Linux the default app is "Test Editor", I
would like to configure fman so that Gvim is the default apps for text
files.

**Comment by pburns001** [comment]
Never mind, I found that if I set the default app for a file on Ubuntu,
then fman uses the default app and it works as I desire.  Thanks for the
help!

**Comment by raguay** [comment]
No problem. Glad to help.
