### ISSUE TITLE
Plugin favoritepairs Issue saving  directory

### ISSUE THREAD

**Issue by Alex1q1** [fman-community/fman#816]
I have an issue with the plugin "favorite pair".When i am saving "favorite pair" it work some time right but when it go wrong fman is saving this directory like this "C:\Users\Windows10\C:Users\Windows10".When i am onening the fman again i recive a massage "Colud not load folder C:\Users\Windows10\C:Users\Windows10".I tried to reinstall but it didn't work.

**Comment by mherrmann** [comment]
Hi, when we were in touch by email, I meant that the best place to ask your question is on the issue tracker of the plugin. I'm not sure whether by "favorite pair" you mean the plugin https://github.com/raguay/favorites. But either way, because I am not maintaining these other plugins, I am going to close this issue here.
